-- c5rdk0_162981_fl_pd.ml001292 definição
 
CREATE TABLE `ml001292` (
  `ID` int(11) NOT NULL,
  `companyid` int(11) DEFAULT NULL,
  `cardid` int(11) DEFAULT NULL,
  `documentid` int(11) DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  `tableid` text,
  `anonymization_date` date DEFAULT NULL,
  `anonymization_user_id` text,
  `auxi_atividade` text,
  `processInstanceId` text,
  `text_status_chamado` text,
  `txt_protocolo` text,
  `txt_solicitante` text,
  `txt_email_solicitante` text,
  `txt_dt_solicitacao` text,
  `gestor` text,
  `cat_area` text,
  `zcat_area` text,
  `cat_infra_sistemas` text,
  `zcat_empresas` text,
  `cat_sistema` text,
  `zcat_sistema` text,
  `cat_servico` text,
  `zcat_servico` text,
  `txt_num_titulo` text,
  `txt_detalhe_sol` text,
  `sel_info_pagamento` text,
  `txt_info_pagamento` text,
  `txt_motivo_complemento` text,
  `sel_aprov_comprov` text,
  `txt_aprov_comprov` text,
  `txt_motivo_recusa` text,
  `txt_motivo_recusa_val` text,
  `cat_subarea` text,
  `zcat_subarea` text,
  `txt_sla` text,
  `sel_tipo_demanda` text,
  `txt_tipo_demanda` text,
  `sel_classificacao` text,
  `txt_classificacao` text,
  `txt_obs_n1` text,
  `txt_obs_seguranca` text,
  `txt_obs_sustentacao` text,
  `txt_obs_infra` text,
  `apAvaliar` text,
  `obsapAvaliar` text,
  `apAvaliarNPS` text,
  `apAvaliarMOTIVO` text,
  `apAvaliarOUTROS` text,
  `obsapAvaliar_val` text,
  `obsapAvaliar_val1` text,
  `obsapAvaliar_val2` text,
  `txt_apAvaliarNPS` text,
  `txt_apAvaliarMOTIVO` text,
  `sel_tipo_demanda_n1` text,
  `txt_tipo_demanda_n1` text,
  `txt_sla1` text,
  `sel_severidade` text,
  `txt_severidade` text,
  `sel_resolvido` text,
  `txt_resolvido` text,
  `txt_complemento_demanda` text,
  `sel_aprov_gestor` text,
  `txt_aprov_gestor` text,
  `txt_obs_gestor` text,
  `txt_obs_sol_periferico` text,
  `obsapAvaliar_val3` text,
  `txt_complemento_demanda_val` text,
  `txt_obs_n1_val` text,
  `cat_unidade` text,
  `zcat_unidade` text,
  `cat_depositante` text,
  `zcat_depositante` text,
  `txt_chamado_externo` text,
  `sel_categoria_problema` text,
  `auxi_atividadeDescricao` text,
  `txt_status_chamado` text,
  `txt_cpf_motorista` text,
  `txt_contratado` text,
  `txt_placa` text,
  `txt_cartao` text,
  `txt_data_emissao` text,
  PRIMARY KEY (`ID`),
  KEY `ML001292I001` (`documentid`,`version`,`companyid`),
  KEY `ML001292I002` (`documentid`,`cardid`,`companyid`),
  KEY `ML001292I003` (`documentid`,`cardid`,`version`,`companyid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;